# apps/platform/sealed-secrets/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: '2.18.0' # Use a specific, recent version
    releaseName: sealed-secrets
    includeCRDs: true
